// @generated by protobuf-ts 2.9.1
// @generated from protobuf file "tmtc_generic_c2a.proto" (package "tmtc_generic_c2a", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { TmtcGenericC2a } from "./tmtc_generic_c2a";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { GetSateliteSchemaResponse } from "./tmtc_generic_c2a";
import type { GetSatelliteSchemaRequest } from "./tmtc_generic_c2a";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service tmtc_generic_c2a.TmtcGenericC2a
 */
export interface ITmtcGenericC2aClient {
    /**
     * @generated from protobuf rpc: GetSatelliteSchema(tmtc_generic_c2a.GetSatelliteSchemaRequest) returns (tmtc_generic_c2a.GetSateliteSchemaResponse);
     */
    getSatelliteSchema(input: GetSatelliteSchemaRequest, options?: RpcOptions): UnaryCall<GetSatelliteSchemaRequest, GetSateliteSchemaResponse>;
}
/**
 * @generated from protobuf service tmtc_generic_c2a.TmtcGenericC2a
 */
export class TmtcGenericC2aClient implements ITmtcGenericC2aClient, ServiceInfo {
    typeName = TmtcGenericC2a.typeName;
    methods = TmtcGenericC2a.methods;
    options = TmtcGenericC2a.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetSatelliteSchema(tmtc_generic_c2a.GetSatelliteSchemaRequest) returns (tmtc_generic_c2a.GetSateliteSchemaResponse);
     */
    getSatelliteSchema(input: GetSatelliteSchemaRequest, options?: RpcOptions): UnaryCall<GetSatelliteSchemaRequest, GetSateliteSchemaResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetSatelliteSchemaRequest, GetSateliteSchemaResponse>("unary", this._transport, method, opt, input);
    }
}
